# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
